### ISSUE TITLE
Error in setup log, is it important?

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/post-installation-setup#10]
When running the installation script, I noticed this in the log:

```
12:49:10 01/22/18 Running: /bin/chown -R jetty:jetty /opt/gluu/jetty/oxauth/custom/libs
12:49:10 01/22/18 Error reading None
12:49:10 01/22/18 Traceback (most recent call last):
  File "/install/community-edition-setup/setup.py", line 763, in readFile
    f = open(inFilePath)
IOError: [Errno 2] No such file or directory: '/etc/redhat-release'

12:49:10 01/22/18 Found package '/opt/dist/oxd/oxd-server_3.1.2-5~trusty+Ub14.04_all.deb' for install
```

It does not seem to be affecting anything, but it's a bit strange.

Environment: ubuntu 14

**Comment by arvindsinghtomar** [comment]
that error is not affected by our script

**Comment by yurem** [comment]
yes, it's not affect setup. In order to detect OS type setup.py is trying to read this file. And if it not exists it reads from /etc/os-release'.

I've removed this error message: https://github.com/GluuFederation/community-edition-setup/commit/407a02ab408fbe23ec0b964032fc67528defd00a
