### ISSUE TITLE
Errors importing ldif data with openDJ

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/post-installation-setup#13]
I found problems when using a Gluu server CE backed by openDJ LDAP...

Here is the log of installation script:

[setup.log](https://github.com/GluuFederation/post-installation-setup/files/1661361/setup.log)

As result, the 2 custom scripts are not being added to scripts branch :(

**Comment by yurem** [comment]
Fixed.
The message in log:
`
15:07:37 01/25/18 Traceback (most recent call last):
  File "/install/community-edition-setup/setup.py", line 2441, in deleteLdapPw
    os.remove(os.path.join(self.ldapBaseFolder, 'opendj-setup.properties'))
OSError: [Errno 2] No such file or directory: '/opt/opendj/opendj-setup.properties'
`
we can ignore becuase it just attempt to delete OpenDJ setup properties file.

In any case I fixed this in setup: https://github.com/GluuFederation/community-edition-setup/commit/cdcb003b3b0d6774d101b742b42da23b4024cebb
