### ISSUE TITLE
Binary dependency missing for oxd install in centos 6

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/post-installation-setup#17]
See screenshots:

extension binary tried: `gluu-server-ext-3.1.2-1-4.centos6.noarch`
![oxd_installation_failed_centos6](https://user-images.githubusercontent.com/5444180/35484327-9f18f516-041c-11e8-9376-9dcb8db4ce98.png)

extension binary tried: `gluu-server-ext-3.1.2-1-8.centos6.noarch`
![oxd_installation_failed_centos6_2](https://user-images.githubusercontent.com/5444180/35484334-a76f490e-041c-11e8-87c2-c9aa1308dacb.png)

Environment:

uname -r outputs `2.6.32-696.el6.x86_64`

Gluu ce installed was: `gluu-server-3.1.2-1-7.centos6.x86_64` 

I get the same kind of error when installing oxd only using the standalone binary package `oxd-server-3.1.2-2.centos6.noarch` outside chroot.

**Comment by yurem** [comment]
CE package is fine:
```
rpm -q oracle-jdk8-provided
oracle-jdk8-provided-112-1.el6.x86_64
```
But according to this oxd package has bug:
```
rpm -ivh oxd-server-3.1.2-2.centos6.noarch.rpm
warning: oxd-server-3.1.2-2.centos6.noarch.rpm: Header V4 RSA/SHA256 Signature, key ID 0544ba38: NOKEY
error: Failed dependencies:
        java-1.8.0-openjdk is needed by oxd-server-3.1.2-2.centos6.noarch
        or is needed by oxd-server-3.1.2-2.centos6.noarch
```

It should requires either `java-1.8.0-openjdk` or `oracle-jdk8-provided`. But current oxd package requires both `java-1.8.0-openjdk` and `or`

**Comment by jgomer2001** [comment]
Testing with newer `gluu-server-ext-3.1.2-1-8.centos6.noarch`, but oxd bundle inside still have problems...

Surprisingly I found that now oxd is in `/opt/oxd-server-ce` not in `/opt/oxd-server`... After changing paths in my local `setup_cred_mgr.py`, still couldn't make it start:
![1](https://user-images.githubusercontent.com/5444180/35600878-38b25270-05fe-11e8-9b47-40829cbd8351.png)

So I did
![2](https://user-images.githubusercontent.com/5444180/35600993-bb99b200-05fe-11e8-8736-ed93e5c996dc.png)

After some time I could tell `/etc/init.d/oxd-server-ce` was still pointing to `/opt/oxd-server`...
![3](https://user-images.githubusercontent.com/5444180/35601025-e1829658-05fe-11e8-9724-c5875df5cad9.png)

Package `gluu-server-ext-3.1.2_1-11~Ub14.04+trusty_all` does have oxd in `/opt/oxd-server`

**Comment by yurem** [comment]
It's oxd package [issue](https://github.com/GluuFederation/oxd/issues/140). oxd service fully depend on environment variable. This is dangerous and led to errors which you mentioned.

>> Surprisingly I found that now oxd is in /opt/oxd-server-ce not in /opt/oxd-server

It's packaging issue. I open separate issue to track [this](https://github.com/GluuFederation/post-installation-setup/issues/19)
