### ISSUE TITLE
oxd service not starting upon vm restart

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/post-installation-setup#18]
Environment: Ubuntu 14 with `gluu-server-ext-3.1.2_1-10~Ub14.04+trusty_all`

After rebooting the VM the oxd service is not up. If one checks `/var/log/oxd-server.log`, it does not show the typical trace of messages when that service starts. 

Example of commands run inside Gluu chroot after the reboot (note the first messages is somewhat misleading):

```
# service oxd-server status
oxd-server is running ...
PID: [5510]

# netstat -nltp
...no entry appears in the list for oxd port (8099) ...

# service oxd-server restart
oxd-server stoping ...
/etc/init.d/oxd-server: 72: kill: No such process

Starting oxd-server ...
PID: [6254]

# netstat -nltp
Now 8099 appears
```

This makes the cred-manager application not usable upon a restart since it requires oxd-server up and running all the time

Additionally, a question is: should oxd be stopped when Gluu-Server is stopped?. eg. after I do

$ sudo service gluu-server-3.1.2 stop
[sudo] password for user: 
Shutting down Gluu Server...
Stopping Apache...
OK
Stopping Credentials Manager...
OK
Stopping oxTrust...
OK
Stopping oxAuth...
OK
Stopping OpendDJ...
OK

I see oxd is still running. Any thoughts?

**Comment by yurem** [comment]
We have following issues:

1. oxd service not starting upon vm restart. cred-manager script should have similar to CE setup script methods to configure service for automatic start
2. gluu-server init script not stop oxd service. We can try to add to after this [lines](https://github.com/GluuFederation/community-edition-package/blob/master/package/initd/gluu-server#L215) one more statement like:
stopGenericService oxd "oxd"

**Comment by yurem** [comment]
Example for point 1:

```
        # Enable service autoload on Gluu-Server startup
        if self.os_type in ['centos', 'fedora', 'redhat']:
            if self.os_initdaemon == 'systemd':
                self.run(["/usr/bin/systemctl", 'enable', serviceName])
            else:
                self.run(["/sbin/chkconfig", serviceName, "on"])
        elif self.os_type in ['ubuntu', 'debian']:
self.run(["/usr/sbin/update-rc.d", serviceName, 'defaults', '50', '25'])
```
and call
```
...self.setup.process_rc_links(self.init_fixes)...
```

**Comment by yurem** [comment]
Please retest it after resolving #19
