### ISSUE TITLE
oxd-server-ce should have same file tree structure and service name

### ISSUE THREAD

**Issue by yurem** [GluuFederation/post-installation-setup#19]
There is major difference in folders structure and service name in compare to oxd package.
Both packages should be the same. The difference should be only in depends directive.

Also oxd-service-ce should has packaging directive to prohibit both packages installation:
Conflicts:          oxd

**Comment by adrian-gluu** [comment]
do you think we should add conflict tag in the spec file with oxd-server for this pkg?
i did a new built with the right init file
https://repo.gluu.org/centos/testing/oxd-server-ce-3.1.2-1.centos6.noarch.rpm

**Comment by yurem** [comment]
Yes, because this will not allow admin to install both oxd-server packages.
Can you rebuild gluu-server-ext-*.rpm ?

**Comment by adrian-gluu** [comment]
this new build has the conflict tag for oxd-server:
https://repo.gluu.org/centos/testing/oxd-server-ce-3.1.2-2.centos6.noarch.rpm
