### ISSUE TITLE
centos 6 rpm 1-12 does not start the installation process

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/post-installation-setup#20]
With https://repo.gluu.org/centos/testing/gluu-server-ext-3.1.2-1-12.centos6.noarch.rpm

Issuing
```
# rpm -i gluu-server-ext-3.1.2-1-12.centos6.noarch.rpm
warning: ... Header V4 RSA/SHA256 signature, key ID 0544ba38: NO KEY
```

The prompt is back immediately

Adding `--nosignature` just makes the warning disappear and same behavior

**Comment by adrian-gluu** [comment]
Jose it looks like the pkg was already signed let me update the repos and please try with YUM not manually:
rpm --addsign gluu-server-ext-3.1.2-1-12.centos6.noarch.rpm
Enter pass phrase:
Pass phrase is good.
gluu-server-ext-3.1.2-1-12.centos6.noarch.rpm:
warning: gluu-server-ext-3.1.2-1-12.centos6.noarch.rpm already contains identical signature, skipping

**Comment by jgomer2001** [comment]
works...
