### ISSUE TITLE
oxd configuration in two places for centos binary

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/post-installation-setup#21]
Using `gluu-server-ext-3.1.2-1-12.centos6.noarch.rpm`... Regarding to cred-manager behavior, all is fine.

After installation script is run, I found oxd config files are in `/etc/oxd/oxd-server/` as expected, but also in `/opt/oxd-server/conf`, which may be confusing for customers. This is not the case of Ubuntu though.

**Comment by adrian-gluu** [comment]
This issue was sorted on the lates oxd-server pkg included on gluu-server-ext:
https://repo.gluu.org/ubuntu/pool/main/trusty-devel/oxd-server_3.1.2-41~trusty+Ub14.04_all.deb

**Comment by jgomer2001** [comment]
How about centos?

**Comment by adrian-gluu** [comment]
Here is centos6
https://repo.gluu.org/centos/testing/oxd-server-ce-3.1.2-12.centos6.noarch.rpm

**Comment by jgomer2001** [comment]
I don't understand, `/opt/oxd-server/conf` is still in that rpm.
But I am closing this issue because cred-manager is not affected by this fact
