### ISSUE TITLE
Adjustments in how cred-manager.json file is generated

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/post-installation-setup#9]
* Produce the file with proper indentation. Currently is a one line file which is hard to read/edit. Even more important: let's do the same for `oxd-conf.json` 

* If oxd-server was installed by means of the installation script, use `localhost` for the property "host" in `cred-manager.json` instead of actual host name: oxd by default expects localhost socket connections.

**Comment by jgomer2001** [comment]
>If oxd-server was installed by means of the installation script, use localhost for the property "host" in cred-manager.json instead of actual host name: oxd by default expects localhost socket connections.

I just see host being set to "None" instead of "localhost"

This is what I see when providing license info 
![cred_mgr_json_license](https://user-images.githubusercontent.com/5444180/35286381-e17d1542-002d-11e8-8e3e-9f06cc8097fc.png)

This is what I see when license info is not provided
![cred_mgr_json_no_license](https://user-images.githubusercontent.com/5444180/35286408-f2668a82-002d-11e8-98ad-dc07ab1bdb73.png)

**Comment by jgomer2001** [comment]
When providing https extension option, that is after hitting **2** when this appears:
```
 Will this product use localhost [1] or https [2] to connect to oxd-server. [1|2] ? [1] :
```

The `host` property is not being set properly. Example

if I entered: `https://do.it.right:123",

`host` property in **cred-manager.json** should end up being  `do.it.right`. Currently it's just setting it to the whole URL.

The `port` is set being correctly.

A question is, if I hit anthing other than **1**, it takes as if one typed **2**. Is that fine?

**Comment by arvindsinghtomar** [comment]
The host property is not being set properly. Example
if I entered: `https://do.it.right:123",

if you enable https oxd-server 
that time only used host name (https url + post) 
it's not used to port

**Comment by arvindsinghtomar** [comment]
A question is, if I hit anything other than 1, it takes as if one typed 2. Is that fine?
